# @package _group_
name: GCN
norm: true
norm_type: DAD
loop: true
loop_value: 1
partition: 'metis'
compensate: false
score_func_name: 'linear'
mlp_init:
  use: False
  epochs: 50
  log: False
  shared_optim: False
optim_name: 'Adam'
optim:
  SGD:
    momentum: 0.0
    dampening: 0.0
    nesterov: False
  Adagrad:
    lr_decay: 0
  Adadelta:
    rho: 0
  RMSprop:
    alpha: 0.99
    momentum: 0.0
    centered: False
  Adam:
    amsgrad: False
  NAdam:
    momentum_decay: 0.004
params:
  proteins: 0
  ppa: 0

  reddit:
    architecture:
      num_layers: 2
      hidden_channels: 256
      dropout: 0.5
      drop_input: false
      batch_norm: false
      residual: false
    num_parts: 200
    batch_size: 100
    max_steps: 2
    pool_size: 2
    num_workers: 0
    lr: 0.01
    reg_weight_decay: 0.0
    nonreg_weight_decay: 0.0
    grad_norm: none
    epochs: 400

  ppi:
    architecture:
      num_layers: 2
      hidden_channels: 1024
      dropout: 0.0
      drop_input: false
      batch_norm: true
      residual: true
      linear: true
    num_parts: 20
    batch_size: 2
    max_steps: 10
    pool_size: 2
    num_workers: 0
    lr: 0.005
    reg_weight_decay: 0.0
    nonreg_weight_decay: 0.0
    grad_norm: null
    epochs: 1000

  flickr:
    architecture:
      num_layers: 2
      hidden_channels: 256
      dropout: 0.3
      drop_input: true
      batch_norm: true
      residual: false
    num_parts: 24
    batch_size: 12
    max_steps: 2
    pool_size: 2
    num_workers: 0
    lr: 0.01
    reg_weight_decay: 0
    nonreg_weight_decay: 0
    grad_norm: null
    epochs: 400

  yelp:
    architecture:
      num_layers: 2
      hidden_channels: 512
      dropout: 0.0
      drop_input: false
      batch_norm: false
      residual: true
      linear: false
    num_parts: 40
    batch_size: 5
    max_steps: 4
    pool_size: 2
    num_workers: 0
    lr: 0.01
    reg_weight_decay: 0
    nonreg_weight_decay: 0
    grad_norm: null
    epochs: 500

  arxiv:
    architecture:
      num_layers: 3
      hidden_channels: 256
      dropout: 0.0
      drop_input: false
      batch_norm: true
      residual: false
      bn_name: 'BatchNorm1d'
      beta: 1.0
    num_parts: 80
    batch_size: 40
    max_steps: 2
    pool_size: 2
    num_workers: 0
    lr: 0.01
    reg_weight_decay: 0
    nonreg_weight_decay: 0
    grad_norm: none
    epochs: 300
    runs: 1

  products:
    architecture:
      num_layers: 3
      hidden_channels: 256
      dropout: 0.3
      drop_input: false
      batch_norm: false
      residual: false
    num_parts: 7
    batch_size: 1
    max_steps: 4
    pool_size: 1
    num_workers: 0
    lr: 0.005
    reg_weight_decay: 0
    nonreg_weight_decay: 0
    grad_norm: null
    epochs: 300
    runs: 1
